import { useState } from "react";
import { motion } from "framer-motion";
import { Loader2, ChefHat } from "lucide-react";
import { useHealth } from "@/contexts/HealthContext";
import { generateRecipe } from "@/lib/gemini";
import { useToast } from "@/hooks/use-toast";

interface GroceryItem {
  id: string;
  name: string;
  qty: string;
  price: number;
  category: string;
  checked: boolean;
}

const initialItems: GroceryItem[] = [
  { id: "1", name: "Chicken Breast", qty: "500g", price: 220, category: "🥩 Proteins", checked: false },
  { id: "2", name: "Salmon Fillet", qty: "300g", price: 380, category: "🥩 Proteins", checked: false },
  { id: "3", name: "Broccoli", qty: "2 heads", price: 60, category: "🥦 Vegetables", checked: false },
  { id: "4", name: "Spinach", qty: "200g", price: 40, category: "🥦 Vegetables", checked: true },
  { id: "5", name: "Brown Rice", qty: "1 kg", price: 90, category: "🌾 Grains", checked: false },
  { id: "6", name: "Quinoa", qty: "500g", price: 150, category: "🌾 Grains", checked: false },
  { id: "7", name: "Greek Yogurt", qty: "400g", price: 80, category: "🧴 Dairy", checked: true },
  { id: "8", name: "Eggs", qty: "12 pcs", price: 70, category: "🧴 Dairy", checked: false },
  { id: "9", name: "Apples", qty: "6 pcs", price: 60, category: "🍎 Fruits", checked: false },
  { id: "10", name: "Bananas", qty: "1 dozen", price: 50, category: "🍎 Fruits", checked: false },
];

const fadeUp = { hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0 } };

export default function GroceryPage() {
  const { healthData, preferences } = useHealth();
  const { toast } = useToast();

  const [items, setItems] = useState<GroceryItem[]>(initialItems);
  const [budget, setBudget] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const toggle = (id: string) => setItems((prev) => prev.map((i) => i.id === id ? { ...i, checked: !i.checked } : i));

  const handleGenerate = async () => {
    if (!budget || isNaN(Number(budget))) {
      toast({ title: "Invalid Budget", description: "Please enter a valid number for budget in ₹.", variant: "destructive" });
      return;
    }

    setIsGenerating(true);

    // Convert to number for prompt to ensure Gemini understands it's purely a value
    const numBudget = Number(budget);

    const prompt = `You are a professional nutrition AI assistant. Generate a healthy grocery list for a user in India.
User's budget: ₹${numBudget}
User's health data: HR ${healthData.heartRate}, SpO2 ${healthData.spo2}%, Sleep ${healthData.sleepHours}h, Stress ${healthData.stress}/10.
User preferences: Vegetarian: ${preferences.isVegetarian}, Indian cuisine: ${preferences.isIndian}.

Generate a grocery list optimizing for their health limits (e.g. low stress/good sleep) while STRICTLY keeping the total estimated price under or exactly at the budget of ₹${numBudget}.
The items should be categorized properly (e.g., "🥦 Vegetables", "🥩 Proteins", "🌾 Grains"). 
Respond ONLY with a valid JSON array of objects. Each object must have these exact keys:
- "name" (item name)
- "qty" (amount, e.g., "500g", "1 kg")
- "price" (estimated price strictly as a NUMBER without currency symbol)
- "category" (the category string with an emoji, like "🍎 Fruits")`;

    try {
      const text = await generateRecipe(prompt);
      const cleanedText = text.replace(/```json/g, "").replace(/```/g, "").trim();
      const newItems = JSON.parse(cleanedText).map((item: any, index: number) => ({
        ...item,
        id: Date.now().toString() + index,
        checked: false
      }));
      setItems(newItems);
    } catch (err) {
      console.error(err);
      toast({ title: "Generation failed", description: "Could not generate grocery list. Try again.", variant: "destructive" });
    } finally {
      setIsGenerating(false);
    }
  };

  const categories = [...new Set(items.map((i) => i.category))];
  const checkedCount = items.filter((i) => i.checked).length;
  const total = items.reduce((s, i) => s + i.price, 0);

  return (
    <motion.div initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: 0.08 } } }} className="max-w-6xl mx-auto">
      <motion.div variants={fadeUp} className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Smart Grocery List 🛒</h1>
          <p className="text-sm text-muted-foreground">Generated by AI based on your health & budget</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground font-medium">₹</span>
            <input
              type="number"
              placeholder="Enter budget..."
              value={budget}
              onChange={(e) => setBudget(e.target.value)}
              className="pl-8 pr-4 py-2 w-36 rounded-xl bg-card border border-border text-sm outline-none focus:ring-1 focus:ring-primary"
            />
          </div>
          <button onClick={handleGenerate} disabled={isGenerating} className="btn-press flex items-center justify-center gap-2 h-10 px-4 rounded-xl bg-gradient-to-r from-orange-400 to-rose-400 hover:from-orange-500 hover:to-rose-500 text-white font-medium shadow-md transition-all">
            {isGenerating ? <Loader2 size={16} className="animate-spin" /> : <ChefHat size={16} />}
            Auto-Fill List
          </button>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Grocery List */}
        <motion.div variants={fadeUp} className="lg:col-span-2 space-y-4">
          {isGenerating ? (
            <div className="glass-card flex flex-col items-center justify-center min-h-[400px]">
              <ChefHat className="w-12 h-12 text-muted-foreground animate-bounce mb-3" />
              <p className="font-medium text-foreground">Creating your optimal grocery list...</p>
              <p className="text-sm text-muted-foreground">Checking local prices & nutritional needs</p>
            </div>
          ) : items.length === 0 ? (
            <div className="glass-card flex flex-col items-center justify-center min-h-[400px]">
              <p className="text-muted-foreground">List is empty. Enter a budget to auto-fill!</p>
            </div>
          ) : categories.map((cat) => (
            <div key={cat}>
              <p className="text-sm font-medium text-muted-foreground mb-2">{cat}</p>
              <div className="space-y-2">
                {items.filter((i) => i.category === cat).map((item) => (
                  <motion.div
                    key={item.id}
                    layout
                    className={`glass-card p-3 flex items-center gap-3 cursor-pointer transition-opacity ${item.checked ? "opacity-50" : ""}`}
                    onClick={() => toggle(item.id)}
                    whileTap={{ scale: 0.98 }}
                  >
                    <div className={`w-5 h-5 rounded-md border-2 flex items-center justify-center transition-colors ${item.checked ? "bg-primary border-primary" : "border-border"}`}>
                      {item.checked && <span className="text-primary-foreground text-xs">✓</span>}
                    </div>
                    <div className="flex-1">
                      <p className={`text-sm font-medium text-foreground ${item.checked ? "line-through" : ""}`}>{item.name}</p>
                      <p className="text-xs text-muted-foreground">{item.qty}</p>
                    </div>
                    <p className="text-sm text-muted-foreground">₹{item.price}</p>
                  </motion.div>
                ))}
              </div>
            </div>
          ))}
        </motion.div>

        {/* Sidebar */}
        <motion.div variants={fadeUp} className="space-y-4">
          {/* Summary */}
          <div className="glass-card p-5">
            <h3 className="font-semibold text-foreground mb-3">Summary</h3>
            <p className="text-2xl font-bold text-foreground">₹{total}</p>
            <p className="text-xs text-muted-foreground mb-3">Total Estimate</p>
            <div className="w-full h-2 rounded-full bg-muted overflow-hidden">
              <motion.div className="h-full rounded-full bg-gradient-to-r from-primary to-secondary" initial={{ width: 0 }} animate={{ width: `${(checkedCount / items.length) * 100}%` }} />
            </div>
            <p className="text-xs text-muted-foreground mt-2">{checkedCount} of {items.length} items collected</p>
            <button className="btn-press w-full mt-4 py-2.5 rounded-xl border border-border text-foreground text-sm font-medium">
              Share List 📤
            </button>
          </div>

          {/* Sustainability */}
          <div className="glass-card p-5">
            <h3 className="font-semibold text-foreground mb-3">🌱 Sustainability</h3>
            <div className="flex items-center gap-4">
              <div className="relative w-16 h-16">
                <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                  <circle cx="18" cy="18" r="15.5" fill="none" stroke="hsl(var(--muted))" strokeWidth="3" />
                  <circle cx="18" cy="18" r="15.5" fill="none" stroke="hsl(var(--primary))" strokeWidth="3" strokeDasharray={`${73} ${100 - 73}`} strokeLinecap="round" />
                </svg>
                <span className="absolute inset-0 flex items-center justify-center text-sm font-bold text-primary">73%</span>
              </div>
              <p className="text-sm text-muted-foreground">This week's meals are 73% eco-friendly</p>
            </div>
          </div>
        </motion.div>
      </div>
    </motion.div>
  );
}
